schema: http://localhost:6222/graphql
extensions:
  customDirectives:
    - "directive @connection(key: String!, filters: [String]) on FIELD"
  codegen:
    generates:
      "schema.graphql":
        plugins:
          - schema-ast
      "__schema__/schema.json":
        plugins:
          - introspection
